blueprint:
  name: Lichtsteuerung mit Motion, Lux & Tür-Bypass
  description: >
    Schaltet Lichter über Bewegung & Helligkeit, mit Tür-Bypass:
    - ON-Bypass (Tür offen = immer an)
    - OFF-Bypass (Tür offen = nicht ausschalten)
    - Automation-Bypass (Tür offen = keine Automatik)
  domain: automation
  source_url: https://example.com/light_motion_lux_door_bypass

  input:
    target_lights:
      name: Lichter
      description: Welche Lichter sollen geschaltet werden?
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    motion_sensors:
      name: Bewegungsmelder
      description: Bewegungsmelder für diese Szene.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    lux_sensor:
      name: Lux-Sensor (optional)
      description: Sensor für die Helligkeit (Lux). Leer lassen = Lux wird ignoriert.
      default: null
      selector:
        entity:
          domain: sensor

    min_lux:
      name: Mindest-Lux
      description: Unterhalb dieses Werts werden die Lichter eingeschaltet (wenn Bewegung erkannt wird).
      default: 50
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: lx
          mode: box

    door_bypass_on:
      name: Türsensor – ON-Bypass
      description: >
        Wenn diese Tür "offen" ist, werden die Lichter eingeschaltet
        und bleiben an, unabhängig von Lux und Bewegung. Leer lassen = nicht benutzt.
      default: null
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - door
            - opening

    door_bypass_off:
      name: Türsensor – OFF-Bypass
      description: >
        Wenn diese Tür "offen" ist, werden die Lichter NICHT automatisch ausgeschaltet.
        (z.B. Tür auf = bleib an). Leer lassen = nicht benutzt.
      default: null
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - door
            - opening

    door_bypass_automation:
      name: Türsensor – Automation-Bypass
      description: >
        Wenn diese Tür "offen" ist, wird die komplette Automation ignoriert.
        Es erfolgt weder Auto-An noch Auto-Aus. Leer lassen = nicht benutzt.
      default: null
      selector:
        entity:
          domain: binary_sensor
          device_class:
            - door
            - opening

    off_delay:
      name: Ausschaltverzögerung
      description: Wie lange nach letzter Bewegung soll gewartet werden, bevor das Licht ausgeschaltet wird?
      default: "00:03:00"
      selector:
        time: {}

mode: restart
max_exceeded: silent

variables:
  motion_sensors: !input motion_sensors
  lux_sensor: !input lux_sensor
  min_lux: !input min_lux
  door_bypass_on: !input door_bypass_on
  door_bypass_off: !input door_bypass_off
  door_bypass_automation: !input door_bypass_automation
  off_delay: !input off_delay

trigger:
  # Bewegung erkannt
  - platform: state
    entity_id: !input motion_sensors
    to: "on"

  # Bewegung beendet
  - platform: state
    entity_id: !input motion_sensors
    to: "off"

  # ON-Bypass Tür geöffnet/geschlossen
  - platform: state
    entity_id: !input door_bypass_on

  # OFF-Bypass Tür geöffnet/geschlossen
  - platform: state
    entity_id: !input door_bypass_off

  # Automation-Bypass Tür geöffnet/geschlossen
  - platform: state
    entity_id: !input door_bypass_automation

  # HA Start, um Zustand zu synchronisieren
  - platform: homeassistant
    event: start

condition: []

action:
  # === GLOBAL: Automation-Bypass prüfen ===
  - condition: template
    alias: "Automation-Bypass aktiv?"
    value_template: >
      {{
        not door_bypass_automation
        or is_state(door_bypass_automation, 'off')
      }}

  - choose:
      # === Lichter einschalten ===
      - alias: "Lichter einschalten bei Bewegung oder ON-Bypass"
        conditions:
          - condition: template
            value_template: >
              {{
                trigger.platform in ['state', 'homeassistant'] and (
                  (
                    trigger.platform == 'state'
                    and trigger.to_state is not none
                    and trigger.to_state.state == 'on'
                    and (
                      trigger.entity_id == motion_sensors
                      or (door_bypass_on and trigger.entity_id == door_bypass_on)
                    )
                  )
                  or trigger.platform == 'homeassistant'
                )
              }}
          - condition: template
            alias: "Lux-Bedingung oder ON-Bypass erfüllt"
            value_template: >
              {% set on_bypass_active = door_bypass_on and is_state(door_bypass_on, 'on') %}
              {% if on_bypass_active %}
                {{ true }}
              {% else %}
                {% if not lux_sensor %}
                  {{ true }}
                {% else %}
                  {% set st = states(lux_sensor) %}
                  {% if st in ['unknown', 'unavailable', 'none', ''] %}
                    {{ false }}
                  {% else %}
                    {{ (st | float(999999)) < min_lux }}
                  {% endif %}
                {% endif %}
              {% endif %}
        sequence:
          - service: homeassistant.turn_on
            target: !input target_lights

      # === Lichter ausschalten (Auto-Off) ===
      - alias: "Lichter ausschalten nach Verzögerung, wenn keine Bewegung & kein Bypass"
        conditions:
          - condition: template
            value_template: >
              {{
                trigger.platform == 'state'
                and trigger.entity_id == motion_sensors
                and trigger.to_state is not none
                and trigger.to_state.state == 'off'
              }}
        sequence:
          - delay: "{{ off_delay }}"

          # Sicherstellen, dass der Bewegungsmelder immer noch "off" ist
          - condition: state
            entity_id: !input motion_sensors
            state: "off"

          # ON-Bypass: wenn Tür offen -> NICHT ausschalten
          - condition: template
            value_template: >
              {{ not door_bypass_on or is_state(door_bypass_on, 'off') }}

          # OFF-Bypass: wenn Tür offen -> NICHT ausschalten
          - condition: template
            value_template: >
              {{ not door_bypass_off or is_state(door_bypass_off, 'off') }}

          - service: homeassistant.turn_off
            target: !input target_lights
    default: []
