blueprint:
  name: 'Flurlicht – kombiniert (Aqara P2 + SONOFF) mit Reset & Recent-Hold'
  description: >
    'Hält das Flurlicht an, solange Aqara P2 oder SONOFF (PIR/mmWave) Präsenz/Bewegung melden
    ODER innerhalb eines Haltefensters ("recent activity") zuletzt aktiv waren. Optionaler
    manueller Reset (input_button / input_boolean) schaltet sofort aus. Mit Tag/Nacht-Helligkeit
    und optionaler Helligkeitsschwelle (Lux).'
  domain: automation
  source_url: 'https://example.local/blueprints/flur_licht_kombiniert_reset.yaml'

  input:
    aqara_sensors:
      name: 'Aqara Sensor(en)'
      description: 'Wähle deinen Aqara P2 (motion/presence) Binary-Sensor(en).'
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    sonoff_sensors:
      name: 'SONOFF Sensor(en)'
      description: 'Wähle SONOFF SNZB-06P (presence) oder SNZB-03 (motion) Binary-Sensor(en).'
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    light_target:
      name: 'Licht(e) im Flur'
      selector:
        target:
          entity:
            domain: light

    off_grace:
      name: 'Nachlaufzeit bis AUS (Sekunden)'
      description: 'Zeit, die nach letzter Belegung gewartet wird, bevor ausgeschaltet wird.'
      default: 120
      selector:
        number:
          min: 10
          max: 900
          unit_of_measurement: s
          mode: slider
          step: 5

    recent_hold:
      name: 'Recent-Activity Haltefenster (Sekunden)'
      description: 'So lange gilt die letzte Aktivität noch als „belegt“, auch wenn Sensoren bereits „aus“ sind.'
      default: 30
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: s
          mode: slider
          step: 5

    night_start_hour:
      name: 'Nachtmodus Start (Stunde 0–23)'
      default: 23
      selector:
        number:
          min: 0
          max: 23
          mode: box

    night_end_hour:
      name: 'Nachtmodus Ende (Stunde 0–23)'
      default: 6
      selector:
        number:
          min: 0
          max: 23
          mode: box

    day_brightness:
      name: 'Helligkeit Tag (%)'
      default: 80
      selector:
        number:
          min: 1
          max: 100
          mode: slider

    night_brightness:
